spring:
  application:
    name: api-gateway

server:
  port: 4040
  
zuul:
  routes:
    BloodDonor-rest-api:
      path: /rest/**
      service-id: donor-service
      url: http://localhost:8080/api/v1/donors
      strip-prefix: false
    
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"